title: 0xCARNEMUERTA
description: >
  Blog and portfolio of a cloud-native, security-aware data/ML engineer

baseurl: "/0xcarnemuerta.github.io" # Note the leading slash
url: "https://eclayj.github.io"

theme: minima

header_pages:
  - about.md
  - certs.md	

sass:
  style: compressed

include:
  - assets/css/custom.css

show_excerpts: true
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/page:num/"

defaults:
  -
    scope:
      path: ""
    values:
      head_custom: head.html


# Trigger rebuild