title: 0xCARNEMUERTA
description: >
  Blog and portfolio of a cloud-native, security-aware data/ML engineer
baseurl: ""
url: "https://eclayj.github.io/0xcarnemuerta.github.io"
theme: minima

header_pages:
  - about.md

sass:
  style: compressed

include:
  - assets/css/custom.css
